### ISSUE TITLE
Fix Enemies

### ISSUE THREAD

**Issue by nightblade9** [MuslimGamer/Backeroids#22]
- [x] Kamikazes shouldn't track you; they should initially point at you, but if you move, they're now still pointing at your old position
- [x] Kamikazes are too fast to dodge
- [x] Mines are too small
- [x] Mines shouldn't move
- [x] Mines should explode after some time (10-15s?)

**Comment by nightblade9** [comment]
Can you please take care of these if you get time @NegativeScript

**Comment by NegativeScript** [comment]
These are fixed in #23. Do check it out, and let me know if further adjustments are required.
