### ISSUE TITLE
Extreme Lag

### ISSUE THREAD

**Issue by nightblade9** [MuslimGamer/Backeroids#27]
Ran into this today -- if you just keep turning constantly and hold down space to keep shooting, the game starts to really crawl after a minute or so.

Could be related to a bug during development where kamikazes never moved on-screen -- but still bears investigation. Are we cleaning up everything we should be?

**Comment by NegativeScript** [comment]
The problem could be the fact that every single HelixSprite instance is unique, while we could've reused cached sprites.

**Comment by nightblade9** [comment]
Without profiling and investigating, there's no way to know. Premature and blind optimization often causes more problems. Let's not jump to conclusions just yet :)

**Comment by nightblade9** [comment]
This hasn't come back, and you did a pretty good job with killing off-screen entities. I think it's safe to close this.
